# This image can be used to speed up the test writing/run cycles.
# Build using the following from the root of this project:
# docker build -f spec/acceptance/nodesets/docker/Dockerfile-mycentos-dev spec/acceptance/nodesets/docker/ -t mycentos:dev

FROM centos:7

# You will need to copy the ca-wa-12.52-sp01-cr09a-linux-x86-64.zip as this is not included in this repository.
COPY ./ca-wa-12.52-sp01-cr09a-linux-x86-64.zip /tmp/
COPY ./puppetlabs-pc1.repo /etc/yum.repos.d/puppetlabs-pc1.repo

RUN yum install -y binutils gcc keyutils-libs.i686 libidn.i686 libidn.so.11 libstdc++.i686 libXext.i686 libXrender.i686 libXtst.i686 ncurses-libs.i686 unzip \
puppet-agent httpd sudo openssh-server openssh-clients curl ntpdate

# RUN /opt/puppetlabs/bin/puppet module install puppet-archive \
# && /opt/puppetlabs/bin/puppet module install puppetlabs-concat \
# && /opt/puppetlabs/bin/puppet module install puppetlabs-stdlib \
# && /opt/puppetlabs/bin/puppet module install puppetlabs-apache
