# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  forge_modules:
    apache:  "puppetlabs/apache"
    archive: "puppet/archive"
    concat:  "puppetlabs/concat"
#    stdlib:  "puppetlabs/stdlib"
  symlinks:
    ca_sso_web_agent: "#{source_dir}"
